### ISSUE TITLE
Feature Request - upgrade to latest gosling.js

### ISSUE THREAD

**Issue by matandro** [gosling-lang/streamlit-gosling#1]
Hello team,

Is there a chance that this will be upgraded soon?
I was able to get the dependencies working with packge.json
```json
"dependencies": {
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "gosling.js": "^0.16.0",
    "higlass": "^1.13.4",
    "pixi.js": "^6.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.1",
    "typescript": "^4.9.5",
    "streamlit-component-lib": "^2.0.0",
    "web-vitals": "^1.0.1"
  },
```

but when I tried to build it failed because 'getViewIds' does not exist on type 'GoslingApi' any more (since V 0.10)

**Comment by wangqianwen0418** [comment]
Hi @matandro , thanks for submitting the issue! 
Yes, we plan to update streamlit-gosling to the latest Gosling sometime this Month.

**Comment by wangqianwen0418** [comment]
Thanks to @etowahadams, we've updated streamlit-gosling to v0.1.4, incorporating the latest gosling.js v0.17.0. I'm closing this issue now.
